---
kind: pipeline
type: docker
name: default

clone:
  depth: 1

steps:
  - name: docker buildx
    image: git.hd.caiweiqiang.cn:5001/drone-plugins/docker-buildx
    privileged: true
    settings:
      registry: git.hd.caiweiqiang.cn:5001
      username: caiweiqiang
      password:
        from_secret: gitea.token
      repo: git.hd.caiweiqiang.cn:5001/${DRONE_REPO}
      platform: linux/amd64,linux/arm64
      cache: s3
      cache_s3_bucket: drone-ci-cache
      cache_s3_endpoint: https://minio.hd.caiweiqiang.cn:5001
      cache_s3_access_key:
        from_secret: minio.access_key
      cache_s3_secret_key:
        from_secret: minio.secret_key
      cache_mode: max
      cache_ignore_error: false

node:
  ID: my-pve-runner
