version: '3.7'
services:
  awsbpm:
    build: .
    image: awsbpm:6.2.GA-all-in-one
    volumes:
      - awsbpm-db_data:/var/lib/mysql
      - awsbpm-app_doccenter:/AWSBPM/doccenter
    ports:
      - 3306:3306/tcp
      - 8088:8088/tcp
      - 8000:8000/tcp
volumes:
  awsbpm-db_data:
  awsbpm-app_doccenter: